---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openslo.openslo
  resources:
  - alertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - alertconditions/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - alertconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - alertnotificationtargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - alertnotificationtargets/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - alertnotificationtargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - alertpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - alertpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - alertpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - slis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - slis/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - slis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - slos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - slos/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - slos/status
  verbs:
  - get
  - patch
  - update
