---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openslo.openslo
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.openslo
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - openslo.openslo
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
