apiVersion: openslo.com/v1
kind: Datasource
metadata:
  labels:
    app.kubernetes.io/name: mimir-infra-ds
  name: mimir-infra-ds
spec:
  description: Mimir Datasource for logging tenant
  type: mimir
  connectionDetails:
    address: https://mimir.monitoring.dev.heu.group/
    address: http://localhost:9009/
    sourceTenants:
      - gatekeeper-system
    targetTenant: gatekeeper-system
      - monitoring
    targetTenant: monitoring
