apiVersion: openslo.com/v1
kind: SLI
metadata:
  labels:
    app.kubernetes.io/name: sli
    app.kubernetes.io/instance: sli-sample
    app.kubernetes.io/part-of: slo-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slo-kubernetes-operator
  name: sli-sample
spec:
  description: testing SLI
  ratioMetric:
    counter: true
    good:
      metricSource:
        metricSourceRef: datasource-sample
        type: Prometheus
        spec: |
          controller_runtime_reconcile_total{job="keda-operator", result="success"}
    bad:
      metricSource:
        metricSourceRef: datasource-sample
        type: Prometheus
        spec: |
          controller_runtime_reconcile_total{job="keda-operator", result="error"}
    total:
      metricSource:
        metricSourceRef: datasource-sample
        type: Prometheus
        spec: |
          controller_runtime_reconcile_total{job="keda-operator"}
