apiVersion: openslo.openslo/v1
kind: AlertPolicy
metadata:
  labels:
    app.kubernetes.io/name: alertpolicy
    app.kubernetes.io/instance: alertpolicy-sample
    app.kubernetes.io/part-of: slo-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slo-kubernetes-operator
  name: alertpolicy-sample
spec:
  description: Alert policy for cpu usage breaches, notifies on-call devops via email
  alertWhenBreaching: true
  alertWhenResolved: false
  # TODO(fourstepper): test for inline and Ref
  conditions: []
  # TODO(fourstepper): test for inline and Ref
  notificationTargets: []
